### ISSUE TITLE
FeatureTimeMaxAcf.m - issue comparing empty arrays?

### ISSUE THREAD

**Issue by jhtu** [alexanderlerch/ACA-Code#2]
I was trying to figure out how this function works by playing implementing the same functionality in Python.  In doing so, I'm not sure if I may have stumbled upon a bug, or if perhaps I am not understanding the function correctly.

In line 40, eta_tmp may take on the value [] (empty array) if the find() function does not find any afCorr values below the threshold.  Then in line 41, the comparison between eta_min and eta_tmp will select the empty array, as this is apparently how Matlab's max() function handles them.  (As it turns out, Python is different and will select the non-empty value over the empty array.)

Then starting in line 44, a similar process happens.  And here, even if in line 45 a non-zero value is found for eta_tmp, in line 46, if eta_min has already taken on the value [] (due to line 41), then a comparison with the new value of eta_tmp will again select the empty array.  I am not sure if this is the desired functionality.

I see that in line 48, there is a check to account for empty arrays, where eta_min is set to the default value if it has taken on the value [].  Perhaps this same check should happen between the code blocks starting on lines 40 and 44, respectively?  I think that might fix the issue of empty arrays dominating the max() calls.

**Comment by alexanderlerch** [comment]
Good catch, thanks! I didn't have time to verify, but I boldly submitted what I think fixes this. Let me know if you continue to have problems. Thanks!
