### ISSUE TITLE
Spectrogram

### ISSUE THREAD

**Issue by ghost** [alexanderlerch/ACA-Code#3]
In spectral features, X denotes spectrogram with dimension: (fftlength) cross (observation). but when I put the spectrogram in let just say FeatureSpectralCentroid.m, it gives me an array of values instead of single value. Whats the matter?

Note: I'm using y=spectrogram(signal) in MATLAB to obtain spectrogram

**Comment by alexanderlerch** [comment]
This is intended behavior: you receive an output vector of length observations as one feature value per magnitude spectrum is computed. You can verify by cross-checking with my ComputeFeature function. You can aggregate the features per file or file segment by computing, for example, their mean and standard deviation.

**Comment by ghost** [comment]
and what if I input spectrum??? I went through the code and that's why I'm asking....

**Comment by alexanderlerch** [comment]
if you input only one column of the spectrogram, you will receive exactly one output value. Just make sure each row of the spectrogram is only the magnitude spectrum and doesn't contain any mirrored components.
