### ISSUE TITLE
Is magnitude spectrum X in ComputeFeature.m right？

### ISSUE THREAD

**Issue by chongjg** [alexanderlerch/ACA-Code#4]
In ComputeFeature.m, line 78"X           = abs(X)*2/iBlockLength;"
Should that be changed into "X=abs(X)^2/iBlockLength"

**Comment by alexanderlerch** [comment]
Yes, this is correct. There are different ways of normalizing a magnitude spectrum - this one is the one I use (although it does not account for the window). If you square the spectrum, you will get the power spectrum, not the magnitude spectrum, which is not what we want here.

**Comment by chongjg** [comment]
I got it. Thank you very much for reply.
