### ISSUE TITLE
some how it shows that f is unused !! 

### ISSUE THREAD

**Issue by ghost** [alexanderlerch/ACA-Code#5]
% in the real world, we would do this block by block...
        [X,f,t]     = spectrogram(  afAudioData,...
                                    afWindow,...
                                    iBlockLength-iHopLength,...
![1111](https://user-images.githubusercontent.com/58721083/74635307-f3c26d00-518f-11ea-8676-2a371bc4639d.PNG)

                                    iBlockLength,...
                                    f_s);

>>>>
 [v_sc,t] = ComputeFeature('SpectralCentroid', afAudioData, fs);
Error using spectrogram
Too many input arguments.

Error in ComputeFeature (line 71)
         [X,t]     = spectrogram(
         afAudioData,...

**Comment by alexanderlerch** [comment]
These are two different issues. 
1. The warning message ('f' is unused) means that you do not use this variable in your code. That is not a problem if you don't want to use it.
2. The error message is a different problem. It seems you have a different spectrogram function in your Matlab path. Could you debug into that function and see what toolbox it is from? Do you have the Signal Processing Toolbox installed?
