### ISSUE TITLE
FeatureSpectralSpread: Hz to bin conversion

### ISSUE THREAD

**Issue by kaushalsali** [alexanderlerch/ACA-Code#8]
Bug in conversion of spectral centroid from Hz to bin index. 
On line 13 of `FeatureSpectralSpread.m`, `size(X,1)` should be `(size(X,1)-1)`. 

https://github.com/alexanderlerch/ACA-Code/blob/36bcd3cb5f036cef8f6e2ed82fc30b7419f9495f/FeatureSpectralSpread.m#L13

**Comment by alexanderlerch** [comment]
This had been fixed in https://github.com/alexanderlerch/ACA-Code/commit/f90bc903ffce6f2e2467f4710cf154e16be430f0#diff-985bbb47ca38e208080b2a2a8c6713fac792ae95a56f288b5806b993f64da248
