### ISSUE TITLE
FeatureTimeMaxAcf: Convert hardcoded values to optional params

### ISSUE THREAD

**Issue by kaushalsali** [alexanderlerch/ACA-Code#9]
The following hardcoded variables in `FeatureTimeMaxAcf` should be converted to optional parameters for maintaining consistency with alexanderlerch/pyACA@bf275613debc53f411beba7ffa41f45d2655dc54.

https://github.com/alexanderlerch/ACA-Code/blob/36bcd3cb5f036cef8f6e2ed82fc30b7419f9495f/FeatureTimeMaxAcf.m#L17-L18

**Comment by alexanderlerch** [comment]
this was fixed in https://github.com/alexanderlerch/ACA-Code/commit/83de75fb89625e3c6c42727253cd96976f3f08c7#diff-8de7d263067e7d7f129a44510d8b3718ff9c9e095b358dd7f68bae01207c4e7d
